### ISSUE TITLE
Felaktig beräkning

### ISSUE THREAD

**Issue by nordtektiger** [SimonTrossing/CGPA-calculator#1]
Bra stil på koden, tyvärr genererar den inte korrekt GPA dock. Fixa!!

Percentage | Letter Grade | Unweighted GPA
-|-|-
97-100%|A+|4.0
93-96%|A|4.0
90-92%|A-|3.7
87-89%|B+|3.3
83-86%|B|3.0
80-82%|B-|2.7
77-79%|C+|2.3
73-76%|C|2.0
70-72%|C-|1.7
67-69%|D+|1.3
65-66%|D|1.0
<65%|F|0.0

Datan tagen från https://gpacalculate.com/percentage-grade-calculator

**Comment by SimonTrossing** [comment]
Okej🤣

**Comment by nordtektiger** [comment]
Tips: När du har fixat ett problem, så kan du stänga denna konversationen. Det är ofta vanligt att hänvisa till den specifika committen som fixade det, t.ex. 07b97b8b7ef454748f23a94f536303f8644c53ae i detta fallet.
